Fix tsc error (#152)
Fix the following:

```
src/editorDecorator.ts:88:7 - error TS2739: Type '{ enviroPath: string; enviroName: string; unitName: string; functionName: string; testName: string; }' is missing the following properties from type 'testNodeType': enviroNodeID, testFile, testStartLine

88       testNode = {
         ~~~~~~~~


Found 1 error in src/editorDecorator.ts:88
```