Run tsc before running vitest (#151)
Tests are now type-checked with `tsc` before running `vitest`.

In the coded_mock branch, we would have received:

```
tests/unit/utils.ts:135:31 - error TS2345: Argument of type 'TextDocuments' is not assignable to parameter of type 'TextDocument'.
  Type 'TextDocuments' is missing the following properties from type 'TextDocument': uri, languageId, version, getText, and 3 more.

135   return getTstCompletionData(documents, completion);
```

and the tests wouldn't have run.